camposP2 <- c("ID_registro",
  "autor_nome_cientifico",
  "subespecie",
  "autor_subespecie",
  "variedade",
  "autor_variedade",
  "herbario_origem",
  "tombo_herbario_origem",
  "cod_barras_herbario_origem",
  "registro_duplicado",
  "Nome_coletor_original",
  "numero_coletor",
  "ano_coleta",
  "mes_coleta",
  "dia_coleta",
  "estado",
  "municipio",
  "localidade",
  "long_original",
  "lat_original",
  "sist_coord_original",
  "datum_original",
  "situacao_coordenada",
  "altitude",
  "determinador_original",
  "ano_determinacao",
  "mes_determinacao",
  "dia_determinacao",
  "tipo_veg_habitat",
  "fonte_dados") %>% tibble(campo =.)

todos_os_nomes <- simplify(names_raw) %>% unique() %>% sort() %>% tibble(field = .)
write_csv(camposP2, "output/p2/07_campos_P2.csv")
write_csv(todos_os_nomes, "output/p2/08_campos_originales.csv")
